version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/mongo:/data/db
    
  ns:
    image: nightscout/cgm-remote-monitor
    container_name: ns
    restart: unless-stopped
    environment:
      - MONGODB_URI="mongodb://mongodb:27017"
    env_file:
      - .env      
    depends_on:
      - mongodb
      
  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - ns
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    command: /bin/sh -c "envsubst  '$${NS_HOST}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"      
